import:
  - globals/globals
  - globals/uw2-globals
  - globals/spookyfox-globals
  - orgs/spookyfox/catalog/terraform/tfstate-backend
  - orgs/spookyfox/catalog/terraform/vpc
  - orgs/spookyfox/catalog/terraform/eks-cluster

vars:
  stage: dev


terraform:
  vars: {}

helmfile:
  vars: {}

components:
  terraform:
    "infra/vpc":
      vars:
        ipv4_primary_cidr_block: 172.20.0.0/18