workflows:
  init:
    description: bootstrap environment
    stack: sf-uw2-dev
    type: atmos
    steps:
      - command: terraform init infra/tfstate-backend
      - command: terraform apply infra/tfstate-backend
  vpc:
    description: build vpc
    stack: sf-uw2-dev
    type: atmos
    steps:
      - command: terraform init infra/vpc
      - command: terraform apply infra/vpc
  eks-cluster:
    description: build eks cluster
    stack: sf-uw2-dev
    type: atmos
    steps:
      - command: terraform init infra/eks-cluster
      - command: terraform apply infra/eks-cluster
  helm:
    description: add helm charts
    stack: sf-uw2-dev
    type: atmos
    steps:
      - command: terraform init infra/helm
      - command: terraform apply infra/helm
  destroy:
    description: tear down env
    stack: sf-uw2-dev
    type: atmos
    steps: 
      - command: terraform destroy infra/helm
      - command: terraform destroy infra/eks-cluster
      - command: terraform destroy infra/vpc